@host = https://localhost
@port = 7045

@Restaurants.API_HostAddress = https://localhost:7045

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=4
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
    "Name": "Salumeria",
    "Description": "A culinary experience like no other",
    "Category": "Fine Dining",
    "HasDelivery": true,
    "ContactEmail": "info@salumeria.gr",
    "ContactNumber": "+30 210 1234567",
    "City": "Patra",
    "Street": "Trion Navrachon 24",
    "PostalCode": "12345"
}