@host = https://localhost
@port = 7045

@Restaurants.API_HostAddress = https://localhost:7045

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=8
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
    "Name": "Sirtaki",
    "Description": "Best Greek Cuisine in town",
    "Category": "Greek",
    "HasDelivery": true,
    "ContactEmail": "info@sirtaki.gr",
    "ContactNumber": "1234567890",
    "City": "London",
    "Street": "4567 Maximilian St.",
    "PostalCode": "12345"
}