@host = https://localhost
@port = 7045

@Restaurants.API_HostAddress = https://localhost:7045

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=5
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
    "Name": "Taste Bites",
    "Description": "A cozy restaurant serving a variety of dishes",
    "Category": "International Cuisine",
    "HasDelivery": false,
    "ContactEmail": "info@tastebites.gr",
    "ContactNumber": "2101234567",
    "City": "Athens",
    "Street": "Ermou 123",
    "PostalCode": "54321"
}